name: Publish the package to GPR (from releases)

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Authenticates packages to push to GPR
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/alexeyvyduykin/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RELEASE_VERSION: ${{github.event.release.tag_name}}
        
    - name: Build
      run: dotnet build src/WeatherIcons.Avalonia/WeatherIcons.Avalonia.csproj
      
    - name: Create the package
      run: dotnet pack --configuration Release src/WeatherIcons.Avalonia/WeatherIcons.Avalonia.csproj /p:PackageVersion=${{github.event.release.tag_name}}
 
    - name: Publish the package to GPR
      run: dotnet nuget push src/WeatherIcons.Avalonia/bin/Release/*.nupkg --skip-duplicate
